version: '3'
services:
  api-testrest-postgres:
    container_name: api-testrest-postgres
    build: .
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:mysecretpassword@postgres:5432
      PORT: 3000

    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: rest